///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Product {
/*
{
  "name": "sdkdfjsk",
  "image": "fdksjfskd",
  "price": 20000,
  "sell_price": 20000
} 
*/

  String? name;
  String? image;
  int? price;
  int? sellPrice;

  Product({
    this.name,
    this.image,
    this.price,
    this.sellPrice,
  });
  Product.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    image = json["image"]?.toString();
    price = json["price"]?.toInt();
    sellPrice = json["sell_price"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["image"] = image;
    data["price"] = price;
    data["sell_price"] = sellPrice;
    return data;
  }
}
